# Generated by Django 4.0.3 on 2022-03-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default='Nairobi', max_length=20),
        ),
    ]
